intern/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from intern.views import *

app_name = 'intern'
urlpatterns = [ 
	#re_path('',views.Home.as_view(), name='home'),
	url(r'^index/',intern_details.HomeView.as_view(), name='index'),
	url(r'^personaldetail/',intern_details.PersonalDetailView.as_view(), name='personal-detail'),
	url(r'^updatepersonaldetail/(?P<pk>\d*)',intern_details.UpdatePersonalDetailView.as_view(), name='updatepersonal-detail'),
	          
	url(r'^academicdetail/',intern_details.AcademicDetailView.as_view(), name='academic-detail'),
	url(r'^updateacademicdetail/(?P<pk>\d*)',intern_details.UpdateAcademicDetailView.as_view(), name='updateacademic-detail'),
	
	url(r'^projectdetail/',intern_details.ProjectDetailView.as_view(), name='project-detail'),
	url(r'^internship/',Internship.InternshipDetailView.as_view(), name='internship-detail'),
	url(r'^internpost/(?P<company_id>\d+)/(?P<post_id>\d+)/$', Internship.InternPostConnection.as_view(), name='internpost-connection'),
	url(r'^readmessages/(?P<id>\d+)/$',Internship.ReadMessages, name='read-messages'),
	url(r'^givetest/(?P<pk>\d+)/$',testmodule_intern.GiveTestView.as_view(), name='give-test'),
	url(r'^sumittest/',testmodule_intern.SubmitTestView.as_view(), name='submit-test'),
	url(r'^showresult/',testmodule_intern.ShowResultView.as_view(), name='show-result'),
	#re_path(r'^applied/(?P<type>\w+)/$',views.AppliedInternship.as_view(), name='applied-internship'),
	
	#re_path('detail/(?P<pk>[\-\w]+)/$',views.detail_profile, name='account-detail'),
] 

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

interner/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
# from intern import views
from company import views
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from intern.views import  SignIn_SignUp, intern_details
 
urlpatterns = [
    url(r'^checkuser/(?P<type>\w+)/$', SignIn_SignUp.CheckUser, name='check-user'),
    url(r'^checklogin/(?P<type>\w+)/$', SignIn_SignUp.CheckLogin, name='check-login'),
    url(r'^accounts/signup/$', SignIn_SignUp.MySignUpView.as_view(), name='check-signupuser'),
    url(r'^accounts/login/$', SignIn_SignUp.MyLogInView.as_view(), name='check-loginuser'),
    url(r'^admin/', admin.site.urls),
    url(r'^intern/', include('intern.urls')),
    url(r'^company/', include('company.urls')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^$', intern_details.Home.as_view(), name='home'),
    


] 
 
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

intern/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver 
from django.contrib import messages
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.models import UserManager, AbstractBaseUser
from django.contrib.auth.decorators import login_required
import company

# Create your models here.


# class MyUserManager(UserManager):
# 	def create_user(self, is_company, password=None):
# 		user = self.model(
# 				is_company = True
# 			)
# 		user.save(using=self._db)
# 		return user
class User(AbstractUser):
	is_company = models.BooleanField(default= False)

	REQUIRED_FIELDS = ['email']

class InternProfile(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='intern_profile',primary_key=True)

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
	# print('is_intern ===================',instance.is_company)
	
	InternProfile.objects.get_or_create(user = instance)
	if instance.is_company == False:
		# print('create if called')
		InternProfile.objects.get_or_create(user = instance)
	else:
		# print('create else called')
		company.models.CompanyProfile.objects.get_or_create(user = instance)



@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
	# print('is_intern 8888888888888888888888888',instance.is_company)

	if instance.is_company == "True" :
		# print('save if called')
		company.models.CompanyProfile.objects.get_or_create(user = instance)
	else:
		# print('save else is called')
		InternProfile.objects.get_or_create(user = instance)
		

class PersonalDetails(models.Model):
	internprofile = models.OneToOneField(InternProfile, on_delete=models.CASCADE, related_name='personal_details')
	name = models.CharField(max_length=25)
	email = models.EmailField(max_length=25)
	contact_number = models.BigIntegerField(max_length=10)
	current_city = models.CharField(max_length=25)
	second_city = models.CharField(max_length=25)

class AcademicDetails(models.Model):
	internprofile = models.OneToOneField(InternProfile, on_delete=models.CASCADE)
	schoolname_10 = models.CharField(max_length=30)
	percentage_10 = models.FloatField()
	marksheet_10 = models.FileField()
	schoolname_12 = models.CharField(max_length=30)
	percentage_12 = models.FloatField()
	marksheet_12 = models.FileField()
	college_name = models.CharField(max_length=50)
	current_year = models.IntegerField()
	marksheet_clg = models.FileField()
	cpi = models.FloatField()

class ProjectDetails(models.Model):
	internprofile = models.ForeignKey(InternProfile, on_delete=models.CASCADE)
	title = models.CharField(max_length=20)
	typeof_project = models.CharField(max_length=20)
	description = models.TextField(max_length=500)
	project_link = models.URLField()

intern/views/Internship.py
#import code; code.interact(local=dict(globals(), **locals()))
from django.views import View
from django.shortcuts import render, HttpResponseRedirect, get_object_or_404, redirect, HttpResponse, render_to_response
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from intern.models import *
from company.models import *
from intern.forms import *
from company.forms import *
from django.forms.models import inlineformset_factory
from django.views.generic.edit import FormView
from django.views.generic.edit import CreateView,UpdateView
from django.views.generic import TemplateView
from django.views import generic
from django.urls import reverse_lazy
from allauth.account.views import * 
from allauth.socialaccount.models import * 
from django.contrib.auth import authenticate
from django.http import JsonResponse
from django.core import serializers
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.conf.urls import *
from django.db.models.query import QuerySet
from django.conf import settings
from django.core.files.storage import FileSystemStorage
from django.views.generic.detail import SingleObjectMixin
import datetime
import json
from intern.service.Internship_service import *
from braces.views import LoginRequiredMixin

class InternshipDetailView(TemplateView):
	model = PostDetails
	
	template_name = 'intern/internship.html'
	

	
	def get_context_data(self, **kwargs):
			data = dict()
			page = self.request.GET.get('page')

			if AcademicDetails.objects.filter(internprofile_id = self.request.user.id).exists():
				data['AD'] = AcademicDetails.objects.get(internprofile_id = self.request.user.id).pk

			if PersonalDetails.objects.filter(internprofile_id = self.request.user.id).exists():
				data['PD'] = PersonalDetails.objects.get(internprofile_id = self.request.user.id).pk
	
	
	
			internship = InternshipDetailViewService()
			p = internship.internships(self)
			

			data['data']=p
			paginator = Paginator(p, 3)
			data['data'] = paginator.get_page(page)
			return data
		
			

	

class InternPostConnection(SingleObjectMixin, TemplateView):
	
	def get(self, request, *args, **kwargs):
		
		self.object = self.request.user

		if self.object.id != None:
			id1 = kwargs['company_id']
			id2 = kwargs['post_id']
			if PersonalDetails.objects.filter(internprofile_id= self.object.id).exists() == False:
				
				return HttpResponseRedirect('/intern/personaldetail/')	

			if UserPostConnection.objects.filter(company_id=id1, internprofile_id= self.object.id,postdetails_id=id2).exists():
				return HttpResponseRedirect('/intern/internship/')
			else:
				id1 = kwargs['company_id']
				id2 = kwargs['post_id']
				
				upc = InternPostConnectionService()
				upc.user_postconnection(request, id1, id2)
				
				return HttpResponseRedirect('/intern/internship')
		else:

			return HttpResponseRedirect('/accounts/login/')
	


 
def ReadMessages(request,id):
	upc_details = UserPostConnection.objects.filter(postdetails_id=id)
	
	for upc in upc_details:
		Messages.objects.filter(postdetails_id=upc.postdetails_id).update(is_read="True")

	return HttpResponse(status = 200)

intern/views/SignIn_SignUp.py
#import code; code.interact(local=dict(globals(), **locals()))
from django.views import View
from django.shortcuts import render, HttpResponseRedirect, get_object_or_404, redirect, HttpResponse, render_to_response
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from intern.models import *
from company.models import *
from intern.forms import *
from company.forms import *
from django.forms.models import inlineformset_factory
from django.views.generic.edit import FormView
from django.views.generic.edit import CreateView,UpdateView
from django.views.generic import TemplateView
from django.views import generic
from django.urls import reverse_lazy
from allauth.account.views import * 
from allauth.socialaccount.models import * 
from django.contrib.auth import authenticate
from django.http import JsonResponse
from django.core import serializers
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.conf.urls import *
from django.db.models.query import QuerySet
from django.conf import settings
from django.core.files.storage import FileSystemStorage
from django.views.generic.detail import SingleObjectMixin
import datetime
import json


def CheckUser(request, type):

	if type == "intern":
		request.session['user'] = 'intern'
		return HttpResponseRedirect('/accounts/signup/')

	elif type == "company":
		request.session['user'] = 'company'
		return HttpResponseRedirect('/accounts/signup/')


		
class MySignUpView(SignupView):
	# def form_valid(self, form):
	# 	return HttpResponseRedirect('/accounts/signup')

	def form_valid(self, form):
		#self.user = form.save(self.request)
		data = self.request.session.get('user')
		print(data)
		
		self.user = form.save(self.request)		

		if data == 'company':
			self.user.is_company = True
			self.user.save()
			
		return HttpResponseRedirect('/accounts/login/')

	
def CheckLogin(request, type):
	if type == "intern":
		request.session['user'] = 'intern'
		return HttpResponseRedirect('/accounts/login/')

	elif type == "company":
		request.session['user'] = 'company'
		return HttpResponseRedirect('/accounts/login/')


class MyLogInView(LoginView):

	def form_valid(self, form):
		data = self.request.session.get('user')
		
		if data == 'company':
			return HttpResponseRedirect('/company/contactdetail/')
		elif data == 'intern':
			return HttpResponseRedirect('/intern/index/')

	def post(self, request):
		PD = PersonalDetails.objects.all()
		AD = AcademicDetails.objects.all()		
		CD = ContactDetails.objects.all()
		user = authenticate(username=self.request.POST.get('login'),password=self.request.POST.get('password'))
		login(request, user)
		if not user is None:
			if user.is_company:
				for i in CD:
					if i.company_id == self.request.user.id:
						return HttpResponseRedirect('/company/applications/')
				return HttpResponseRedirect('/company/contactdetail/')
			else:
				for i in PD:					
					if i.internprofile_id == self.request.user.id:
						return HttpResponseRedirect('/intern/index/')
				return HttpResponseRedirect('/intern/personaldetail/')
		return HttpResponseRedirect('/accounts/login/')

intern/views/intern_details.py
#import code; code.interact(local=dict(globals(), **locals()))
from django.views import View
from django.shortcuts import render, HttpResponseRedirect, get_object_or_404, redirect, HttpResponse, render_to_response
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from intern.models import *
from company.models import *
from intern.forms import *
from company.forms import *
from django.forms.models import inlineformset_factory
from django.views.generic.edit import FormView
from django.views.generic.edit import CreateView,UpdateView
from django.views.generic import TemplateView
from django.views import generic
from django.urls import reverse_lazy
from allauth.account.views import * 
from allauth.socialaccount.models import * 
from django.contrib.auth import authenticate
from django.http import JsonResponse
from django.core import serializers
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.conf.urls import *
from django.db.models.query import QuerySet
from django.conf import settings
from django.core.files.storage import FileSystemStorage
from django.views.generic.detail import SingleObjectMixin
import datetime
import json

def InternProfileView(request):
	 
	#profile_form = InternProfileForm()
	if request.method == 'POST':
		user_form = UserForm(request.POST, prefix='UF')
		#profile_form = InternProfileForm(request.POST, prefix='PF')
		if user_form.is_valid():
			user = user_form.save(commit=False) 
			# profile = profile_form.save(commit = False)
			user.save()

		else:
			messages.error(request,("correct erroe=rs"))
	else:
		#import code; code.interact(local=dict(globals(), **locals()))

		user_form = UserForm(prefix='UF')
		#profile_form = InternProfileForm(prefix='PF')
		#print('hello')
	return render(request, 'intern/profile.html',{
			'user_form': user_form,
			#'profile_form': profile_form,
		})


class Home(TemplateView):
	
	template_name = 'intern/home1.html'
	def dispatch(self, request, *args, **kwargs):
		# if 'company' in request.session:
		# 	print('not there')	
		# super(Home, self).dispatch(request, *args, **kwargs)
		return super(Home, self).dispatch(request, *args, **kwargs)

class PersonalDetailView(CreateView):

	model = PersonalDetails
	#fields = ('name','email','contact_number','current_city','second_city')
	form_class = PersonalDetailsForm
	template_name  = 'intern/personal_detail.html'
	success_url = reverse_lazy('intern:academic-detail')

	def form_valid(self, form):
		print('PD')
		IP = InternProfile.objects.get(user = self.request.user)
		PF = form.save(commit=False)
		PF.internprofile = IP
		return super(PersonalDetailView, self).form_valid(form)

class UpdatePersonalDetailView(UpdateView):
	model = PersonalDetails
	form_class = PersonalDetailsForm
	template_name  = 'intern/personal_detail.html'
	success_url = reverse_lazy('intern:index')	
	
	def dispatch(self, *args, **kwargs):
		#or put some logic here
		print(kwargs['pk'])
		if kwargs['pk'] == '':
			return HttpResponseRedirect('/intern/personaldetail/')
		
		return super(UpdatePersonalDetailView, self).dispatch(*args, **kwargs)
	
	

class AcademicDetailView(CreateView):
	model = AcademicDetails
	#fields = ['schoolname_10','percentage_10','schoolname_12','percentage_12','college_name','current_year','cpi']
	form_class = AcademicDetailsForm
	template_name = 'intern/academic_detail.html'
	success_url = reverse_lazy('intern:project-detail')
	
	def form_valid(self, form):
		IP = InternProfile.objects.get(user = self.request.user)
		PF = form.save(commit=False)
		PF.internprofile = IP
		return super(AcademicDetailView, self).form_valid(form)
	
class UpdateAcademicDetailView(UpdateView):
	model = AcademicDetails
	form_class = AcademicDetailsForm
	template_name = 'intern/academic_detail.html'
	success_url = reverse_lazy('intern:index')

	def dispatch(self, *args, **kwargs):
		#or put some logic here
		if kwargs['pk'] == '':
			return HttpResponseRedirect('/intern/academicdetail/')
		
		return super(UpdateAcademicDetailView, self).dispatch(*args, **kwargs)

class ProjectDetailView(CreateView):
	model = ProjectDetails
	#fields = ['title','typeof_project','description','project_link']
	form_class = ProjectDetailsForm
	template_name = 'intern/project_detail.html'
	success_url = reverse_lazy('intern:index')

	def form_valid(self, form):
		
		IP = InternProfile.objects.get(user = self.request.user)
		PF = form.save(commit=False)
		PF.internprofile = IP
		return super(ProjectDetailView, self).form_valid(form)

class HomeView(TemplateView):
	template_name = 'intern/index.html'
	context_object_name = 'interns'
	
	def get_context_data(self, **kwargs):
		page = self.request.GET.get('page')
		IP = InternProfile.objects.get(user = self.request.user)
		context = super().get_context_data(**kwargs)
		if AcademicDetails.objects.filter(internprofile_id = self.request.user.id).exists():
			context['AD'] = AcademicDetails.objects.get(internprofile_id = self.request.user.id).pk

		if PersonalDetails.objects.filter(internprofile_id = self.request.user.id).exists():
			context['PD'] = PersonalDetails.objects.get(internprofile_id = self.request.user.id).pk
	
		upc= UserPostConnection.objects.filter(internprofile_id = IP.user_id).order_by('-id')
		context['upc'] = upc
		paginator = Paginator(upc, 10)
		context['upc'] = paginator.get_page(page)
		return context

intern/templates/intern/academic_detail.html
{% extends 'intern/home.html'%}
{% load crispy_forms_tags %}
{% load static%}
<!-- <!DOCTYPE >
<html>
<head>
	<link rel="stylesheet" type="text/css" href="{% static 'intern/academicdetail.css' %}" />
	<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css"/>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body> -->
	{% block content %}
	<link rel="stylesheet" type="text/css" href="{% static 'intern/academicdetail.css' %}" />
	<h3 style="text-align: center;font-weight: bolder;">Academic Details</h3>
	<div class="container center_div" >
		<!-- <form action="" method="post" enctype="multipart/form-data">
			{% csrf_token %}
			{{form|crispy }}
			<input class="btn btn-info right" type="submit" name="submit">
			<br><br>
		</form> -->
		{% if form.schoolname_10.value != None %}
		<form action="" method="post" enctype="multipart/form-data">
			{% csrf_token %}


			<div id="div_id_schoolname_10" class="form-group">
				<label for="id_schoolname_10" class="form-control-label  requiredField">
					Schoolname 10<span class="asteriskField">*</span> 
				</label> <div class="form-group form-line"> 
				<input type="text" name="schoolname_10" class="textinput textInput form-control" id="id_schoolname_10" placeholder="SchoolName 10" required="" value="{{form.schoolname_10.value}}"> 
			</div> 
		</div> 
		<div id="div_id_percentage_10" class="form-group"> 
			<label for="id_percentage_10" class="form-control-label  requiredField">
				Percentage 10<span class="asteriskField">*</span> 
			</label> 
			<div class="form-group form-line"> 
				<input type="text" name="percentage_10" class="textinput textInput form-control" id="id_percentage_10" placeholder="Percentage 10" required="" value="{{form.percentage_10.value}}">
			</div>
		</div> 
		<div id="div_id_marksheet_10" class="form-group"> 
			<label for="id_marksheet_10" class="form-control-label  requiredField">
				Marksheet 10<span class="asteriskField">*</span>
			</label> 
			<div class="form-group form-line"> 
				<input type="file" name="marksheet_10" class="clearablefileinput" required="" id="id_marksheet_10" value="{{form.marksheet_10.value}}">
			</div> 
		</div> 
		<div id="div_id_schoolname_12" class="form-group"> 
			<label for="id_schoolname_12" class="form-control-label  requiredField">
				Schoolname 12<span class="asteriskField">*</span> 
			</label> 
			<div class="form-group form-line"> 
				<input type="text" name="schoolname_12" class="textinput textInput form-control" id="id_schoolname_12" placeholder="SchoolName 12" required="" value="{{form.schoolname_12.value}}"> 
			</div> 
		</div>
		<div id="div_id_percentage_12" class="form-group"> 
			<label for="id_percentage_12" class="form-control-label  requiredField">
				Percentage 12<span class="asteriskField">*</span> 
			</label> 
			<div class="form-group form-line">
				<input type="text" name="percentage_12" class="textinput textInput form-control" id="id_percentage_12" placeholder="Percentage 12" required="" value="{{form.percentage_12.value}}">
			</div> 
		</div>
		<div id="div_id_marksheet_12" class="form-group"> 
			<label for="id_marksheet_12" class="form-control-label  requiredField">
				Marksheet 12<span class="asteriskField">*</span>
			</label> 
			<div class="form-group form-line"> 
				<input type="file" name="marksheet_12" class="clearablefileinput" required="" id="id_marksheet_12" value="{{form.marksheet_12.value}}">
			</div> 
		</div> 
		<div id="div_id_college_name" class="form-group">
			<label for="id_college_name" class="form-control-label  requiredField">
				College name<span class="asteriskField">*</span>
			</label>
			<div class="form-group form-line"> 
				<input type="text" name="college_name" class="textinput textInput form-control" id="id_college_name" placeholder="College Name" required="" value="{{form.college_name.value}}">
			</div> 
		</div> 
		<div id="div_id_current_year" class="form-group"> 
			<label for="id_current_year" class="form-control-label  requiredField">
				Current year<span class="asteriskField">*</span> 
			</label> 
			<div class="form-group form-line"> 
				<input type="text" name="current_year" class="textinput textInput form-control" id="id_current_year" placeholder="Current Year" required="" value="{{form.current_year.value}}"> 
			</div> 
		</div> 
		<div id="div_id_cpi" class="form-group"> 
			<label for="id_cpi" class="form-control-label  requiredField">
				Cpi<span class="asteriskField">*</span> 
			</label>
			<div class="form-group form-line"> 
				<input type="text" name="cpi" class="textinput textInput form-control" id="id_cpi" placeholder="Current CPI" required="" value="{{form.cpi.value}}"> </div> 
			</div> 
			<div id="div_id_marksheet_clg" class="form-group">
				<label for="id_marksheet_clg" class="form-control-label  requiredField">
					Marksheet clg<span class="asteriskField">*</span> 
				</label> 
				<div class="form-group form-line	"> 
					<input type="file" name="marksheet_clg" class="clearablefileinput" required="" id="id_marksheet_clg" value="{{form.marksheet_clg.value	}}"> 
				</div>
			</div>

			<input class="btn btn-info right" type="submit" name="submit">
			<br><br>
		</form>
		{% else %}
		<form action="" method="post" enctype="multipart/form-data">
			{% csrf_token %}


			<div id="div_id_schoolname_10" class="form-group">
				<label for="id_schoolname_10" class="form-control-label  requiredField">
					Schoolname 10<span class="asteriskField">*</span> 
				</label> <div class="form-group form-line"> 
				<input type="text" name="schoolname_10" class="textinput textInput form-control" id="id_schoolname_10" placeholder="SchoolName 10" required=""> 
			</div> 
		</div> 
		<div id="div_id_percentage_10" class="form-group"> 
			<label for="id_percentage_10" class="form-control-label  requiredField">
				Percentage 10<span class="asteriskField">*</span> 
			</label> 
			<div class="form-group form-line"> 
				<input type="text" name="percentage_10" class="textinput textInput form-control" id="id_percentage_10" placeholder="Percentage 10" required="">
			</div>
		</div> 
		<div id="div_id_marksheet_10" class="form-group"> 
			<label for="id_marksheet_10" class="form-control-label  requiredField">
				Marksheet 10<span class="asteriskField">*</span>
			</label> 
			<div class="form-group form-line"> 
				<input type="file" name="marksheet_10" class="clearablefileinput" required="" id="id_marksheet_10">
			</div> 
		</div> 
		<div id="div_id_schoolname_12" class="form-group"> 
			<label for="id_schoolname_12" class="form-control-label  requiredField">
				Schoolname 12<span class="asteriskField">*</span> 
			</label> 
			<div class="form-group form-line"> 
				<input type="text" name="schoolname_12" class="textinput textInput form-control" id="id_schoolname_12" placeholder="SchoolName 12" required=""> 
			</div> 
		</div>
		<div id="div_id_percentage_12" class="form-group"> 
			<label for="id_percentage_12" class="form-control-label  requiredField">
				Percentage 12<span class="asteriskField">*</span> 
			</label> 
			<div class="form-group form-line">
				<input type="text" name="percentage_12" class="textinput textInput form-control" id="id_percentage_12" placeholder="Percentage 12" required="">
			</div> 
		</div>
		<div id="div_id_marksheet_12" class="form-group"> 
			<label for="id_marksheet_12" class="form-control-label  requiredField">
				Marksheet 12<span class="asteriskField">*</span>
			</label> 
			<div class="form-group form-line"> 
				<input type="file" name="marksheet_12" class="clearablefileinput" required="" id="id_marksheet_12">
			</div> 
		</div> 
		<div id="div_id_college_name" class="form-group">
			<label for="id_college_name" class="form-control-label  requiredField">
				College name<span class="asteriskField">*</span>
			</label>
			<div class="form-group form-line"> 
				<input type="text" name="college_name" class="textinput textInput form-control" id="id_college_name" placeholder="College Name" required="">
			</div> 
		</div> 
		<div id="div_id_current_year" class="form-group"> 
			<label for="id_current_year" class="form-control-label  requiredField">
				Current year<span class="asteriskField">*</span> 
			</label> 
			<div class="form-group form-line"> 
				<input type="text" name="current_year" class="textinput textInput form-control" id="id_current_year" placeholder="Current Year" required=""> 
			</div> 
		</div> 
		<div id="div_id_cpi" class="form-group"> 
			<label for="id_cpi" class="form-control-label  requiredField">
				Cpi<span class="asteriskField">*</span> 
			</label>
			<div class="form-group form-line"> 
				<input type="text" name="cpi" class="textinput textInput form-control" id="id_cpi" placeholder="Current CPI" required=""> </div> 
			</div> 
			<div id="div_id_marksheet_clg" class="form-group">
				<label for="id_marksheet_clg" class="form-control-label  requiredField">
					Marksheet clg<span class="asteriskField">*</span> 
				</label> 
				<div class="form-group form-line	"> 
					<input type="file" name="marksheet_clg" class="clearablefileinput" required="" id="id_marksheet_clg"> 
				</div>
			</div>

			<input class="btn btn-info right" type="submit" name="submit">
			<br><br>
		</form>

		{%endif %}
	</div>
	{% endblock %}
<!-- </body>
</html> -->

intern/templates/intern/detail.html
<p>
	Jay sojitra
</p>

intern/templates/intern/give_test.html
{% extends 'intern/index.html'%}
{% load intern %}
{% load company%}
{% load static %}

{% block content%}
<link rel="stylesheet" type="text/css" href="{% static 'intern/test.css' %}" />
<div class="container center_div">
	
	<form id="formTest" method="post" action="{% url 'intern:submit-test'%}">
		{% csrf_token %}
		<input type="hidden" name="upc_id" value={{upc_id}}>
		<ul>
			{% for i in questions %}
			<li><label style="font-weight: bolder;" name="questions" id="questions">Question:- {{i.text}}</label></li>
			<textarea id="answer" class="form-control" type="text" name="answers" placeholder="Give Your Answer" required="true"></textarea>
			{% endfor %}
		</ul>
		<button class="btn btn-info right" type="submit">submit</button>
	</form>
</div>

<script>
	
</script>


{% endblock%}

intern/templates/intern/profile.html
	
<form action="" method=post>
	{% csrf_token %}
	{{ user_form.as_p }}
	{{ profile_form.as_p }}
<input type="submit" name="submit">
</form>