company/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from .views import *
from django.conf.urls import url

app_name = 'company'
urlpatterns = [ 
	url(r'^contactdetail/',company_details.ContactDetailsView.as_view(), name='contact-detail'),
	url(r'^postdetail/',company_details.PostDetailsView.as_view(), name='post-detail'),
	url(r'^index/',company_details.Index.as_view(),name='index'),
	url(r'^existingpost/',post.ExistingPost.as_view(),name='existing-post'),
	url(r'^post/',post.PostView.as_view(),name='post'),
	url(r'^allpost/',post.AllPostView.as_view(),name='all-post'),
	url(r'^pastpost/',post.PastPostView.as_view(),name='past-post'),
	url(r'^applications/',applications.ApplicationView.as_view(),name='applications'),
	url(r'^accept/',message.MessageView.as_view(),name='messages'),
	url(r'^savemsg/',message.SaveMsg.as_view(),name='save-messages'),
	url(r'^viewdetails/(?P<id>\d+)/$',applications.ViewDetails.as_view(),name='view-details'),
	url(r'^reject/',applications.RejectView.as_view(),name='reject'),
	url(r'^confirm/',applications.ConfirmView.as_view(),name='confirm'),
	url(r'^confirmintern/(?P<pk>\d+)/$',applications.ConfirmInternView.as_view(),name='confirm-intern'),
	url(r'^rejectintern/(?P<pk>\d+)/$',applications.RejectInternView.as_view(),name='reject-intern'),
	url(r'^listintern/',applications.ListofInternView.as_view(),name='list-intern'),
	url(r'^test/',test_module.GenerateQuestionView.as_view(),name='test'),
	url(r'^listofquestion/(?P<type>\w+)/$',test_module.ListofQuestionView.as_view(),name='listofquestion'),
	url(r'^generatetest/(?P<id>\d+)/$',test_module.GenerateTestView.as_view(),name='generate-test'),
	url(r'^createtest/',test_module.CreateTestView.as_view(),name='create-test'),
	url(r'^result/(?P<id>\d+)/$',test_module.ResultView.as_view(), name='result'),
	url(r'^checkanswer/',test_module.CheckAnswerView.as_view(), name='check-answer'),
	url(r'^countresult/',test_module.CountResultView.as_view(), name='count-result'),
	url(r'^deletesinglequestion/',test_module.DeleteOneQuestionView.as_view(), name='delete-singlequestion'),
	url(r'^deleteallquesitons/',test_module.DeleteAllQuestionView.as_view(), name='delete-allquestion'),

	

	#re_path('link/(?P<type>\d+)$',views.ExistingPost.as_view(),name='existing-post'),
] 

intern/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from intern.views import *

app_name = 'intern'
urlpatterns = [ 
	#re_path('',views.Home.as_view(), name='home'),
	url(r'^index/',intern_details.HomeView.as_view(), name='index'),
	url(r'^personaldetail/',intern_details.PersonalDetailView.as_view(), name='personal-detail'),
	url(r'^updatepersonaldetail/(?P<pk>\d*)',intern_details.UpdatePersonalDetailView.as_view(), name='updatepersonal-detail'),
	          
	url(r'^academicdetail/',intern_details.AcademicDetailView.as_view(), name='academic-detail'),
	url(r'^updateacademicdetail/(?P<pk>\d*)',intern_details.UpdateAcademicDetailView.as_view(), name='updateacademic-detail'),
	
	url(r'^projectdetail/',intern_details.ProjectDetailView.as_view(), name='project-detail'),
	url(r'^internship/',Internship.InternshipDetailView.as_view(), name='internship-detail'),
	url(r'^internpost/(?P<company_id>\d+)/(?P<post_id>\d+)/$', Internship.InternPostConnection.as_view(), name='internpost-connection'),
	url(r'^readmessages/(?P<id>\d+)/$',Internship.ReadMessages, name='read-messages'),
	url(r'^givetest/(?P<pk>\d+)/$',testmodule_intern.GiveTestView.as_view(), name='give-test'),
	url(r'^sumittest/',testmodule_intern.SubmitTestView.as_view(), name='submit-test'),
	url(r'^showresult/',testmodule_intern.ShowResultView.as_view(), name='show-result'),
	#re_path(r'^applied/(?P<type>\w+)/$',views.AppliedInternship.as_view(), name='applied-internship'),
	
	#re_path('detail/(?P<pk>[\-\w]+)/$',views.detail_profile, name='account-detail'),
] 

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

interner/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
# from intern import views
from company import views
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from intern.views import  SignIn_SignUp, intern_details
 
urlpatterns = [
    url(r'^checkuser/(?P<type>\w+)/$', SignIn_SignUp.CheckUser, name='check-user'),
    url(r'^checklogin/(?P<type>\w+)/$', SignIn_SignUp.CheckLogin, name='check-login'),
    url(r'^accounts/signup/$', SignIn_SignUp.MySignUpView.as_view(), name='check-signupuser'),
    url(r'^accounts/login/$', SignIn_SignUp.MyLogInView.as_view(), name='check-loginuser'),
    url(r'^admin/', admin.site.urls),
    url(r'^intern/', include('intern.urls')),
    url(r'^company/', include('company.urls')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^$', intern_details.Home.as_view(), name='home'),
    


] 
 
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

company/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.contrib import messages

from django.contrib.auth.models import AbstractUser
from django.conf import settings
import intern
import datetime

class CompanyProfile(models.Model):
	user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, primary_key=True, related_name='company_profile')

# @receiver(post_save, sender=settings.AUTH_USER_MODEL)
# def create_user_profile(sender, instance, created, **kwargs):
# 	print('****', created)
# 	print('company',instance.is_company)
# 	if instance.is_company == 'True':
# 		CompanyProfile.objects.get_or_create(user = instance)
# 	else:
# 		intern.models.InternProfile.objects.get_or_create(user= instance)


# @receiver(post_save, sender=settings.AUTH_USER_MODEL)
# def save_user_profile(sender, instance, **kwargs):
# 	# data= request.session.get('user')
# 	# print("@nd",data)
# 	if instance.is_company == 'True':
# 		instance.company_profile.save()
# 	else:
# 		intern.models.InternProfile.objects.get_or_create(user= instance)

class ContactDetails(models.Model):
	company = models.OneToOneField(CompanyProfile, on_delete=models.CASCADE)
	company_name = models.CharField(max_length=30)
	hr_fname = models.CharField(max_length=20)
	hr_lname = models.CharField(max_length=20)
	hr_email = models.EmailField()
	website_url = models.URLField()
	location = models.CharField(max_length=50)
	contact_number = models.BigIntegerField()

class PostDetails(models.Model):
	company = models.ForeignKey(CompanyProfile, on_delete=models.CASCADE)
	domain = models.CharField(max_length=20)
	technology = models.CharField(max_length=20)
	numberof_interns = models.IntegerField()
	time_duration = models.IntegerField() 
	stipend = models.IntegerField()
	start_date = models.DateField()
	apply_by = models.DateField()
	typeof_internship = models.CharField(max_length=20)
	status = models.CharField(max_length=10,default="live")

class UserPostConnection(models.Model):
	internprofile = models.ForeignKey(intern.models.InternProfile, on_delete=models.CASCADE)
	company = models.ForeignKey(CompanyProfile, on_delete=models.CASCADE)
	postdetails = models.ForeignKey(PostDetails, on_delete=models.CASCADE)
	status = models.CharField(max_length=25,default="Applied")
	applied_date = models.DateField()
	statusupdate_date = models.DateField()
	
class Messages(models.Model):
	postdetails = models.ForeignKey(PostDetails, on_delete=models.CASCADE)
	upc = models.ForeignKey(UserPostConnection, on_delete=models.CASCADE)
	messages = models.TextField(max_length=500)
	is_read = models.BooleanField(default= False)
	message_date = models.DateField(default=datetime.datetime.now().date())

class Technology(models.Model):
	technology_name = models.CharField(max_length=10)

class Question(models.Model):
	technology = models.ForeignKey(Technology, on_delete=models.CASCADE)
	company = models.ForeignKey(CompanyProfile, on_delete=models.CASCADE)		
	text = models.TextField(max_length=500)

class AnswersHR(models.Model):
	question = models.ForeignKey(Question, on_delete=models.CASCADE)
	text = models.TextField(max_length=500)

class AnswersIntern(models.Model):
	question = models.ForeignKey(Question, on_delete=models.CASCADE)
	text = models.TextField(max_length=500)
	upc = models.ForeignKey(UserPostConnection,on_delete=models.CASCADE)
	is_correct = models.BooleanField(default=False)

class Test(models.Model):
	technology = models.ForeignKey(Technology, on_delete=models.CASCADE)
	creation_date = models.DateField(default=datetime.datetime.now().date())

class QuestionTestMap(models.Model):
	test = models.ForeignKey(Test, on_delete=models.CASCADE)
	question = models.ForeignKey(Question, on_delete=models.CASCADE)

class TestStatus(models.Model):
	status = models.CharField(max_length=20)

class TestApplicationMapping(models.Model):
	upc = models.ForeignKey(UserPostConnection, on_delete=models.CASCADE)
	test = models.ForeignKey(Test, on_delete=models.CASCADE)
	result = models.FloatField(default=0)
	teststatus = models.ForeignKey(TestStatus, on_delete=models.CASCADE, default=0)

class InternStatus(models.Model):
	status = models.CharField(max_length=10)

company/views/applications.py
# import code; code.interact(local=dict(globals(), **locals()))
import datetime 
import json
from django.views import View
from django.shortcuts import render, HttpResponseRedirect, get_object_or_404, redirect, render_to_response
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.template.loader import render_to_string
from django.forms.models import inlineformset_factory
from django.views.generic.edit import FormView
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic import TemplateView
from django.views.generic.list import ListView
from django.urls import reverse_lazy
from django.core.paginator import Paginator
from django.forms.formsets import formset_factory
from django.http import JsonResponse
from django.forms.models import model_to_dict
from django.core import serializers
from company.forms import *
from intern.views import *
from intern.models import *
from company.models import *
from company.service.applications_service import *
from braces.views import LoginRequiredMixin

class ApplicationView(LoginRequiredMixin,TemplateView):
	template_name = 'company/application.html'

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		application  = AplicationViewService()
		di = application.applications(self)
		context['check'] = "app"
		applied_datedesc = di['applied_datedesc']
		applied_dateasc = di['applied_dateasc']
		name_desc = di['name_desc'] 
		name_asc = di['name_asc']
		page = di['page']
		domain = di['domain']
		date = di['date']
		post = PostDetails.objects.filter(technology = domain)
		applicants = application.sorted_applicants(self, applied_datedesc, applied_dateasc, name_desc, name_asc, domain, date)

		context['data'] = PostDetails.objects.all()	
		context['applicants'] = applicants
		paginator = Paginator(applicants, 15)
		context['applicantss'] = paginator.get_page(page)
 
		return context

class ViewDetails(TemplateView):
	template_name = 'company/viewdetail.html'

	def get_context_data(self, 	**kwargs):
		
		context = super().get_context_data(**kwargs)
		pk = kwargs['id']

		intern_detail = ViewApplicationService()
		applicants = intern_detail.viewApplication(self)
	
		context['pk'] = pk
		context['applicants'] = applicants
		return context

class RejectView(View):
	def get(self, request, *args, **kwargs):
		post_id = request.GET.get('idd')
		upc_id = request.GET.get('upc_id')
		reject_msg = request.GET.get('rejectMsg')

		reject_intern = RejectViewService()
		reject_intern.rejectIntern(post_id, upc_id, reject_msg)

		return HttpResponseRedirect('/company/applications/')

class ConfirmView(View):
	def get(self, request, *args, **kwargs):
		post_id = request.GET.get('idd')
		upc_id = request.GET.get('upc_id')
		
		confirm_intern = ConfirmViewService()
		confirm_intern.confirmIntern(post_id, upc_id)
		# upc_obj = UserPostConnection.objects.get(id=upc_id,postdetails_id = post_id)
		# upc_obj.status="Confirmed"
		# upc_obj.statusupdate_date = datetime.datetime.now().date()
		# upc_obj.save()
		return HttpResponseRedirect('/company/applications/')

class ConfirmInternView(TemplateView):
	template_name = 'company/confirmintern.html'

	def get_context_data(self, 	**kwargs):
			
		context = super().get_context_data(**kwargs)
		page = self.request.GET.get('page')
		context['check'] = "confirm"
		company_id = kwargs['pk']
		upc = UserPostConnection.objects.filter(company_id= kwargs['pk'],status=4) 
		context['upc'] = upc
		paginator = Paginator(upc, 5)
		context['upc1'] = paginator.get_page(page)
		return context

class RejectInternView(TemplateView):
	template_name = 'company/rejectintern.html'

	def get_context_data(self, 	**kwargs):
			
		context = super().get_context_data(**kwargs)
		page = self.request.GET.get('page')
		context['check'] = "reject"

		company_id = kwargs['pk']
		upc = UserPostConnection.objects.filter(company_id= kwargs['pk'],status=3) 
		context['upc'] = upc
		paginator = Paginator(upc, 5)
		context['upc'] = paginator.get_page(page)
		return context

class ListofInternView(TemplateView):
	template_name = 'company/listintern.html'

company/views/company_details.py
# import code; code.interact(local=dict(globals(), **locals()))
import datetime 
from django.views import View
from django.shortcuts import render, HttpResponseRedirect, get_object_or_404, redirect, render_to_response
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.template.loader import render_to_string
from django.forms.models import inlineformset_factory
from django.views.generic.edit import FormView
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic import TemplateView
from django.views.generic.list import ListView
from django.urls import reverse_lazy
from django.core.paginator import Paginator
from django.forms.formsets import formset_factory
from django.http import JsonResponse
from django.forms.models import model_to_dict
from django.core import serializers
from company.forms import *
from intern.views import *
from intern.models import *
from company.models import *

class ContactDetailsView(CreateView):
	model = ContactDetails
	form_class = ContactDetailsForm
	template_name = 'company/contact_detail.html'
	success_url = reverse_lazy('company:applications')
	def form_valid(self, form):
		company_profile=CompanyProfile.objects.get(user = self.request.user)
		PF = form.save(commit=False)
		PF.company = company_profile
		PF.save()
		return super(ContactDetailsView, self).form_valid(form)

class PostDetailsView(CreateView):
	model = PostDetails
	form_class = PostDetailsForm
	template_name = 'company/post_detail.html'
	success_url = reverse_lazy('company:all-post')
	def form_valid(self, form):
		print('CPD')
		company_profile = CompanyProfile.objects.get(user = self.request.user)
		PF = form.save(commit=False)
		PF.company = company_profile
		PF.save()
		return super(PostDetailsView, self).form_valid(form)



class Index(TemplateView):
	template_name = 'company/index.html'	

company/views/message.py
# import code; code.interact(local=dict(globals(), **locals()))
import datetime 
from django.views import View
from django.shortcuts import render, HttpResponseRedirect, get_object_or_404, redirect, render_to_response
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.template.loader import render_to_string
from django.forms.models import inlineformset_factory
from django.views.generic.edit import FormView
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic import TemplateView
from django.views.generic.list import ListView
from django.urls import reverse_lazy
from django.core.paginator import Paginator
from django.forms.formsets import formset_factory
from django.http import JsonResponse
from django.forms.models import model_to_dict
from django.core import serializers
from company.forms import *
from intern.views import *
from intern.models import *
from company.models import *
from company.service.message_service import *

class MessageView(TemplateView):
		
	
	def get(self, request, *args, **kwargs):
		post_id = request.GET.get('idd')
		upc_id = request.GET.get('upc_id')
		
		message = MessageViewService()
		message.message(post_id, upc_id)
		response = JsonResponse({'post_id':self.request.GET.get('idd'), 'upc_id': self.request.GET.get('upc_id')}, safe = False)

		return response
	
class SaveMsg(TemplateView):

	def get(self, request, *args, **kwargs):
		data = request.GET.get('message')
		post_id = request.GET.get('post_id')
		upc_id = request.GET.get('upc_id')	

		save_message = SaveMsgService()
		save_message.saveMessage(data, post_id, upc_id)

		return HttpResponseRedirect('/company/applications')

company/templates/company/contact_detail.html
{% extends 'company/index.html'%}
{% load crispy_forms_tags %}
{% load static %}
<!-- <!DOCTYPE>
<html> 
<head>
	<link rel="stylesheet" type="text/css" href="{% static 'company/contactdetail.css' %}" />
	<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css"/>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body> -->
	{% block content %}
	<link rel="stylesheet" type="text/css" href="{% static 'company/newpost.css' %}" />

	<h3 style="text-align: center;"> Contact Details</h3>
	<div class="container center_div">
		<!-- <form action="" method="post">
			{% csrf_token %}
			{{form|crispy }}
			<input class="btn btn-primary right" type='submit' value='submit'>
		</form>
	-->
	<form action="" method="post">
		{% csrf_token %}



		<div id="div_id_company_name" class="form-group">
			<label for="id_company_name" class="form-control-label  requiredField">
				Organization name<span class="asteriskField">*</span> 
			</label> 
			<div class="form-group form-line"> 
				<input type="text" name="company_name" class="textinput textInput form-control" id="id_company_name" placeholder="Organization Name" required=""> 
			</div>
		</div>
		<div id="div_id_hr_fname" class="form-group"> 
			<label for="id_hr_fname" class="form-control-label  requiredField">
				HR's Fisrtname<span class="asteriskField">*</span> 

			</label> 
			<div class="form-group form-line"> 
			<input type="text" name="hr_fname" class="textinput textInput form-control" id="id_hr_fname" placeholder="First Name" required=""> 
		</div> 
	</div> 
	<div id="div_id_hr_lname" class="form-group"> 
		<label for="id_hr_lname" class="form-control-label  requiredField">
			HR's Lastname<span class="asteriskField">*</span>
		</label> 
		<div class="form-group form-line"> 
			<input type="text" name="hr_lname" class="textinput textInput form-control" id="id_hr_lname" placeholder="Last Name" required=""> 
		</div>
	</div>
	<div id="div_id_hr_email" class="form-group"> <label for="id_hr_email" class="form-control-label  requiredField">
		HR's Email-id<span class="asteriskField">*</span> 
	</label>
	<div class="form-group form-line"> 
		<input type="text" name="hr_email" class="textinput textInput form-control" id="id_hr_email" placeholder="Email-id" required="">
	</div> 
</div>
<div id="div_id_website_url" class="form-group">
	<label for="id_website_url" class="form-control-label  requiredField">
		Website url<span class="asteriskField">*</span>
	</label> 
	<div class="form-group form-line">
		<input type="text" name="website_url" class="textinput textInput form-control" id="id_website_url" placeholder="website URL" required=""> 
	</div> 
</div> 
<div id="div_id_location" class="form-group"> 
	<label for="id_location" class="form-control-label  requiredField">
		Location<span class="asteriskField">*</span> 
	</label>
	<div class="form-group form-line">
		<input type="text" name="location" class="textinput textInput form-control" id="id_location" placeholder="Location" required=""> 
	</div>
</div> 
<div id="div_id_contact_number" class="form-group"> 
	<label for="id_contact_number" class="form-control-label  requiredField">
		Mobile Number<span class="asteriskField">*</span> 
	</label> 
	<div class="form-group form-line">
		<input type="text" name="contact_number" class="textinput textInput form-control" id="id_contact_number" placeholder="Contact Number" required=""> 
	</div> 
</div>

<input class="btn btn-primary right" type="submit" value="submit">
</form>
</div>
{% endblock %}
<!-- </body>
	</html> -->

company/templates/company/createtest.html
{% extends 'company/index.html'%}
{% load crispy_forms_tags %}
{% load static %}
{% load company %}
{% load static %}
{% load intern%}

{% block content %}
<div class="main">
	dfds
</div>
{% endblock %}

company/templates/company/generateTest.html
{% extends 'company/index.html'%}
{% load crispy_forms_tags %}
{% load static %}
{% load company %}
{% load static %}
{% load intern%}

{% block content %} 
<link rel="stylesheet" type="text/css" href="{% static 'company/sidenav.css'%}">

<div class="main">
	<ul class="nav nav-tabs">
		
		<li><a href="{% url 'company:listofquestion' type=technology.technology_name %} ">Add Question for {{technology.technology_name}}</a></li>
		
	</li>
</ul> 
</div>


{% block questions %}
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7/jquery.js"></script>
<script src="http://malsup.github.com/jquery.form.js"></script>
<div class="main">
	{% if questions %}
	<div class="btn-delete">
		<input type="checkbox" id="checkAll" class="filled-in chk-col-light-blue">
		<label for="checkAll"> Select all questions</label>
		<button id="preview" class="btn btn-info" type="button" style="float: right;" data-toggle="modal" data-target="#myModal" onclick="previewQuestion({{upc_id}})">Preview</button>
	</div>	
	<br><br>
	<form id="listOfQuestionsForm" method="post" action="{% url 'company:create-test' %}">
		{% csrf_token %}
		<!-- <div class="checkboxes"> -->
		<input type="hidden" name="upc_id" value={{upc_id}}>

		<div class="col-md-11">

			{% for i in questions%}
			{% for j in i.id|answer_hr %}
			<div class="row">
				<div class="col-md-1">
					<!-- <input class="checkBoxClass" type="checkbox" data-question_id="{{i.id}}" name="checkboxes" value="{{i.text}}"> -->
					<input type="checkbox" id="check{{i.id}}" class="filled-in checkBoxClass chk-col-light-blue" data-question_id="{{i.id}}" name="checkboxes" value="{{i.text}}">
					<label for="check{{i.id}}"> </label>
				</div>
				<div class="col-md-9" style="word-wrap: break-word;">
					<label>Question:- {{i.text}}</label><br>
					<label> Ans:-</label> {{j.text}}<br><br>
				</div>
				<div class="col-md-2">
				</div>
			</div>
			{% endfor %}
			{% endfor %}	

		</div>

		<!-- </div> -->

		
		<div id="myModal" class="modal fade" role="dialog">
			<div class="modal-dialog">
				<div class="modal-content">
					<div class="modal-header">
						<button type="button" class="close" data-dismiss="modal">&times;</button>
						<h4 class="modal-title">Selected Questions</h4>
					</div>
					<div id="modalBody" class="modal-body">

					</div>
					<div class="modal-footer">
						<button type="button" class="btn btn-default" data-dismiss="modal" style="float: left;">Close</button>
						<a href="{% url 'company:create-test' %}"><button type="submit" class="btn btn-default"  style="float: right;">Create Test</button></a>

					</div>
				</div>

			</div>
		</div>
	</form>

	{% else%}
	<h3>No questions available. First add question to the question Bank</h3>
	{% endif %}

</div>
<script>
	$("#checkAll").click(function () {
		console.log("dsf");
		$(".checkBoxClass").prop('checked', $(this).prop('checked'));
	});
	

	function previewQuestion(id){
		var questions = [];

		$.each($("input[name='checkboxes']:checked"), function(){            
			questions.push($(this).val());
		});

		if (questions == ''){
			document.getElementById("modalBody").innerHTML = "First select questions.";	
		}
		else{
			document.getElementById("modalBody").innerHTML = questions.join("<hr>");
		}

	}
</script>


{% endblock %}
{% endblock %}

company/templates/company/listintern.html
{% extends 'company/index.html'%}
{% load company %}
{% load static %}
{% load intern%}



{% block content %}
    <link rel="stylesheet" type="text/css" href="{% static 'company/sidenav.css'%}">

<div class="main">
<ul class="nav nav-tabs">
	{% if check == "confirm" %}
    <li id="confirm" class="active"><a href="{% url 'company:confirm-intern' pk=request.user.id%}">Confirmed Interns</a></li>
	{% else%}
    <li id="confirm"><a href="{% url 'company:confirm-intern' pk=request.user.id%}">Confirmed Interns</a></li>
	{% endif %}

	{% if check == "reject" %}
    <li id="reject" class="active"><a href="{% url 'company:reject-intern' pk=request.user.id%}">Rejected Interns</a></li>
	{% else %}
    <li id="reject" ><a href="{% url 'company:reject-intern' pk=request.user.id%}">Rejected Interns</a></li>
	{% endif %}

  
  </ul>
  
 </div>
 <div class="main">
  {% block intern %}
  {%  endblock %}
  </div>
{% endblock%}

company/templates/company/post.html
{% extends 'company/index.html'%}
{% load company %}
{% load static %}
{% load intern%}
{% load intern%}


	{% block content %}
    <link rel="stylesheet" type="text/css" href="{% static 'company/sidenav.css'%}">
	
	<div class="main">
		<ul class="nav nav-tabs">
			{% if check == "all"%}
			<li id="all-post" class="active"><a href="{% url 'company:all-post' %}">All Posts</a></li>
			{% else %}
			<li id="all-post" ><a href="{% url 'company:all-post' %}">All Posts</a></li>
			{% endif %}
			{% if check == "existing"%}
			<li id="existing-post" class="active"><a href="{% url 'company:existing-post' %}">Existing</a></li>
			{% else %}
			<li id="existing-post"><a href="{% url 'company:existing-post' %}">Existing</a></li>
			{% endif %}

			{% if check == "past" %}
			<li id="past-post" class="active"><a href="{% url 'company:past-post'%}">History</a></li>
			{% else %}
			<li id="past-post"><a href="{% url 'company:past-post'%}">History</a></li>
			{% endif %}
			<li style="float: right;"><a href="{% url 'company:post-detail'%}">Create New Post</a>
			</li>
		</ul> 
	</div>

	
	<div class="main"> 
		{% block existingpost %}
		{%  endblock %}
	</div>

	{% endblock%}	